### PR TITLE
Feature/devices promise

### PR DESCRIPTION
**Pull request by clegendre**
loadDriver now supports drivers which returns Promises instead of an array of devices directly

### CODE REVIEW

**Comment by clegendre** [comment]
Hello,

The reason behind this pull request is to support drivers which dynamicaly fetch/load their devices. 
For example:
* a SqueezeBox server providing availables Squeeze players.
* a Security center driver which lists all availables Cameras 
etc.

**Comment by MichaelKohler** [comment]
Hi

Thanks for your PR. Have you had a chance to look at discovery? https://neeoinc.github.io/neeo-sdk/#lib-device-devicebuilder.js-enablediscovery

This is meant exactly for your use case. Is this missing something you would expect and would still make your PR necessary?

Happy to hear back from you.
Michael

**Comment by clegendre** [comment]
Hello, 

I missed this (new?) feature of the SDK!

So, the driver returns only one device (which is the "main" device, the hub or whatever its name), and the brain will call the provided function during discovering process.
In the example below, the function is a continuation of a promise. Does this is supported ?

```javascript  
        this.device.enableDiscovery({  
            headerText: 'MyDriver Hub DeviceType.',
            description: '...'
        }, discovererReturningPromise( this.serverIpAddress ).then( devices => {
            return devices .map( d=>... );
         } ) );
```

This is indeed much cleaner to defer this job to the brain, but this really changes how this type of drivers are built!

Thank you.

**Comment by MichaelKohler** [comment]
> I missed this (new?) feature of the SDK!

This is not new ;)

> In the example below, the function is a continuation of a promise. Does this is supported ?

Looks good on the first view, you can find an example here: https://github.com/NEEOInc/neeo-sdk-examples/blob/master/lib/lifxCloud/LifxCloudController.js#L148

**Pull request closed without merging**
